baseURL: "http://tomvictor.github.io/"
title: tomvictor.dev
# paginate: 5
theme: white
languageCode: 'en-us'

googleAnalytics:  G-DN3BSGRTR7

params:
    profileMode:
        enabled: true
        title: "Tom Victor Vithayathil" # optional default will be site title
        subtitle: "
        #entrepreneur #engineer #techenthusiast #developer\n\n
        "
        imageUrl: "https://avatars.githubusercontent.com/u/14200125?v=4" # optional
        imageTitle: "Tom@Goa" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
          - name: Projects
            url: "projects"
          - name: Posts
            url: "posts"
          - name: About
            url: "about"
          - name: Email
            url: "mailto:mail@tomvictor.dev"
    # ShowShareButtons: true
    ShowCodeCopyButtons: true
    # ShowPostNavLinks: true
  

    socialIcons:
      - name: github
        url: "https://github.com/tomvictor"
      - name: youtube
        url: "https://youtube.com/@buildfromzero"
      - name: twitter
        url: "https://x.com/@vjtomvictor"